sonar.projectKey=AIP-F25-2_MedWhisper
sonar.organization=aip-f25-2
sonar.projectName=MedWhisper
sonar.sourceEncoding=UTF-8

# Path to source code (adjust if backend folder name is different)
sonar.sources=.
sonar.exclusions=**/__pycache__/**, **/*.md, **/.venv/**, **/tests/**, **/*.yml, **/*.yaml

# Python scanning
sonar.language=py
sonar.python.version=3.10

# Optional: include HTML/JS frontend if needed later
# sonar.inclusions=backend/**/*.py

# Test and coverage (you can add later if needed)
# sonar.python.coverage.reportPaths=coverage.xml
