-- Auto-generated staging views for all CSVs

CREATE OR REPLACE VIEW stg_1_hosp_admissions AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/admissions.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_d_hcpcs AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/d_hcpcs.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_d_icd_diagnoses AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/d_icd_diagnoses.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_d_icd_procedures AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/d_icd_procedures.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_d_labitems AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/d_labitems.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_diagnoses_icd AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/diagnoses_icd.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_drgcodes AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/drgcodes.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_emar AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/emar.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_emar_detail AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/emar_detail.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_hcpcsevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/hcpcsevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_labevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/labevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_microbiologyevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/microbiologyevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_omr AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/omr.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_patients AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/patients.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_pharmacy AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/pharmacy.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_poe AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/poe.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_poe_detail AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/poe_detail.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_prescriptions AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/prescriptions.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_procedures_icd AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/procedures_icd.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_services AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/services.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_1_hosp_transfers AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/1_hosp/transfers.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_chartevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/chartevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_d_items AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/d_items.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_datetimeevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/datetimeevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_icustays AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/icustays.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_ingredientevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/ingredientevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_inputevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/inputevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_outputevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/outputevents.csv', header=True, sample_size=-1);;
CREATE OR REPLACE VIEW stg_2_icu_procedureevents AS
SELECT * FROM read_csv_auto('1_data/1_raw/1_mimic-iv-2.1/2_icu/procedureevents.csv', header=True, sample_size=-1);;
